name: ${project.name}
version: ${project.version}
description: ${project.description}
author: moltendorf
website: http://dev.bukkit.org/server-mods/moltendorf-likedynomite/
main: ${project.group}.${project.name}
